### ISSUE TITLE
Error When i Try To Compile

### ISSUE THREAD

**Issue by Gibberditoslumber** [sm64js/sm64js#701]
Terminal Exit Code:
```bash✖ ｢wds｣:  Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1307:21)
    at listenInCluster (node:net:1372:12)
    at doListen (node:net:1510:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/ihlahyconley/sm64js/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ihlahyconley/sm64js/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ihlahyconley/sm64js/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/ihlahyconley/sm64js/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by Agent-11** [comment]
If you're trying to run it on linux try `sudo npm run start` and if that doesn't work, try seeing if anything is using port 80

**Comment by Gibberditoslumber** [comment]
Nope Didn't Work

**Comment by Gibberditoslumber** [comment]
and no i did not have any thing using port 80

**Comment by Gibberditoslumber** [comment]
This Error Code May Lead To Testing
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:67:19)
at Object.createHash (node:crypto:130:10)
at module.exports (/home/ihlahyconley/sm64js/node_modules/webpack/lib/util/createHash.js:135:53)
at NormalModule._initBuildHash (/home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:417:16)
at handleParseError (/home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:471:10)
at /home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:503:5
at /home/ihlahyconley/sm64js/node_modules/webpack/lib/NormalModule.js:358:12
at /home/ihlahyconley/sm64js/node_modules/loader-runner/lib/LoaderRunner.js:373:3
at iterateNormalLoaders (/home/ihlahyconley/sm64js/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
at Array. (/home/ihlahyconley/sm64js/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'

**Comment by Agent-11** [comment]
What OS are you using and what Node JS version are you using?
This seems more like something wrong with Node JS itself maybe, try to see if you can compile any other Node JS project

**Comment by Gibberditoslumber** [comment]
Debian 11

**Comment by Gibberditoslumber** [comment]
dang silent treatment

**Comment by Bloxxel64** [comment]
> dang silent treatment

run these commands, just paste the whole list. then try again.

sudo apt update
sudo apt install nodejs
sudo apt install npm

**Comment by Gibberditoslumber** [comment]
> > dang silent treatment
> 
> run these commands, just paste the whole list. then try again.
> 
> sudo apt update sudo apt install nodejs sudo apt install npm

n o p e it didn't work

**Comment by Bloxxel64** [comment]
> > > dang silent treatment
> > 
> > 
> > run these commands, just paste the whole list. then try again.
> > sudo apt update sudo apt install nodejs sudo apt install npm
> 
> n o p e it didn't work

apt or npm?

**Comment by Bloxxel64** [comment]
@Agent-11 you can close this.

**Comment by Agent-11** [comment]
oh I didn't even realize this thread was still going on until you pinged me

My guess is your node js install is corrupted, don't know how an error with node js internal is relevant to sm64js if everyone can compile perfectly fine.

**Comment by Gibberditoslumber** [comment]
after re-installing Debian It Still Will Not Work
